Vium/Vium/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('accountapp.urls')),
    path('restaurants/', include('restaurantapp.urls')),
    path('orders/', include('orderapp.urls')),
    path('register/', user_views.register, name='register'),
    path('users/', include('users.urls')),
]

Vium/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('accountapp.urls')),
    path('restaurants/', include('restaurantapp.urls')),
    path('orders/', include('orderapp.urls')),
]

orderapp/urls.py
from django.urls import path

from orderapp.views import cash, credit_card, transfer, menu_choice, order_create,base3,cash,order_report


app_name = 'orderapp'

urlpatterns = [
    path('menu_choice/', menu_choice, name='menu_choice'),
    path('order_create/', order_create, name='order_create'),
    path('cash/', cash, name='cash'),
    path('credit_card/', credit_card, name='credit_card'),
    path('transfer/', transfer, name='transfer'),
    path('base3/', base3, name='base3'),
    path('cash/', cash, name='cash'),
    path('order_report/', order_report, name='order_report'),

]

orderapp/models.py
from django.db import models
from django.conf import settings
from django.db import models

# Create your models here.

class Order(models.Model):
    class PaymentMethod(models.TextChoices):
        CASH = 'CASH', '현금결제'
        CREDIT_CARD = 'CREDIT_CARD', '카드결제'
        TRANSFER = 'TRANSFER', '계좌이체'

    class OrderStatus(models.TextChoices):
        WAITING_FOR_RECEIPT = 'WAITING_FOR_RECEIPT', '접수 대기'
        RECEIPT_COMPLETE = 'RECEIPT_COMPLETE', '접수 완료'
        DELIVERY = 'DELIVERY', '배달 중'
        DELIVERY_COMPLETE = 'DELIVERY_COMPLETE', '배달 완료'

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    restaurant = models.ForeignKey('restaurantapp.Restaurant', on_delete=models.CASCADE, related_name='order')
    order_time = models.DateTimeField(auto_now_add=True)
    delivery_status = models.CharField(max_length=20, choices=OrderStatus.choices,
                              default=OrderStatus.WAITING_FOR_RECEIPT)
    address = models.CharField(max_length=255)
    payment_method = models.CharField(max_length=20, choices=PaymentMethod.choices)
    total_price = models.PositiveIntegerField()
    month_total_price = models.PositiveIntegerField()


class OrderMenu(models.Model):
    menu = models.ForeignKey('restaurantapp.Menu', on_delete=models.CASCADE)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_menu')
    name = models.CharField(max_length=255)
    count = models.PositiveIntegerField()
    price = models.PositiveIntegerField()


class OrderOptionGroup(models.Model):
    order_menu = models.ForeignKey('OrderMenu', on_delete=models.CASCADE, related_name='order_option_group')
    name = models.CharField(max_length=255)
    mandatory = models.BooleanField(default=False)


class OrderOption(models.Model):
    order_option_group = models.ForeignKey('OrderOptionGroup', on_delete=models.CASCADE, related_name='order_option')
    name = models.CharField(max_length=255)
    price = models.PositiveIntegerField()

orderapp/forms.py
from django.core.exceptions import ValidationError
from django.db import models
from django.forms import ModelForm

from orderapp.models import Order, OrderMenu, OrderOption, OrderOptionGroup

# 음식 선택
class MenuChoiceForm(ModelForm):

    class Meta:
        model = OrderMenu
        fields = ('id', 'menu', 'name', 'price', 'count')
        # 메뉴 이름, 가게 이름, 가격, 음식 개수
        # 결제 버튼 (장바구니 생략)

''' 주문 기록
class OrderListForm(ModelForm):
    order_menu = OrderMenuForm
    restaurant_name = models.CharField(source='restaurant.name')
    restaurant_image = models.ImageField(source='restaurant.image')

    class Meta:
        model = Order
        fields = ('id', 'order_menu', 'restaurant_name', 'restaurant_image')'''

# 주문 생성
class OrderCreateForm(ModelForm):
    order_menu = MenuChoiceForm

    class Meta:
        model = Order
        fields = ('id', 'payment_method', 'month_total_price')

    '''def validate(self, attrs):
        if attrs['total_price'] < attrs['restaurant'].min_order_price:
            raise ValidationError('total price < restaurant min price')

        self.total_price = 0
        order_menus = attrs['order_menu']
        for order_menu in order_menus:
            self.valid_order_menu(order_menu)

        restaurant = attrs['restaurant']
        delivery_charge = restaurant.delivery_charge if restaurant.delivery_charge is not None else 0
        discount = restaurant.delivery_discount if restaurant.delivery_discount is not None else 0

        if attrs['total_price'] != self.total_price + delivery_charge - discount:
            raise ValidationError('total price != check_price')

        return attrs

    def create(self, validated_data):
        order_menus = validated_data.pop('order_menu')
        order = Order.objects.create(**validated_data)
        for order_menu in order_menus:
            order_option_groups = order_menu.pop('order_option_group')
            order_menu_obj = OrderMenu.objects.create(order=order, **order_menu)
            for order_option_group in order_option_groups:
                order_options = order_option_group.pop('order_option')
                order_option_group_obj = OrderOptionGroup.objects.create(order_menu=order_menu_obj,
                                                                         **order_option_group)
                for order_option in order_options:
                    OrderOption.objects.create(order_option_group=order_option_group_obj, **order_option)
        return order

    def valid_order_menu(self, order_menu):
        menu = order_menu['menu']
        if order_menu['name'] != menu.name:
            raise ValidationError('menu.name != model menu.name')
        if order_menu['price'] != menu.price:
            raise ValidationError('menu.price != model menu.price')

        menu_price = order_menu['price']

        menu_price = menu_price * order_menu['count']
        self.total_price += 'menu_price' '''

orderapp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, ListView, DetailView

from orderapp.forms import OrderCreateForm, MenuChoiceForm
from orderapp.models import Order, OrderMenu



# 음식 선택
def menu_choice(request):
    return render(request, 'orderapp/menu_choice.html', {'menu':'example'})

# 주문 생성
def order_create(request):
    return render(request, 'orderapp/order_create.html')

def cash(request):
    return render(request, 'orderapp/cash.html')

def credit_card(request):
    return render(request, 'orderapp/credit_card.html')

def transfer(request):
    return render(request, 'orderapp/transfer.html')

def base3(request):
    return render(request, 'orderapp/chicken_detailPage.html')

def cash(request):
    return render(request, 'orderapp/cash.html')

def order_report(request):
    return render(request, 'orderapp/order_report.html')

orderapp/templates/orderapp/base_payment.html
<html>
  <head>
    <title>{{menu}}</title>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
    crossorigin="anonymous"
  />
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"
  ></script>
  <style>
    .text-blue {
      color: #6B9BEA;
    }
    .btn-warning {
      --bs-btn-color: #000;
      --bs-btn-bg: #FFE699;
      --bs-btn-border-color: #FFE699;
    }
    .btn-secondary {
      --bs-btn-bg: #D7E1F1;
      --bs-btn-border-color: #D7E1F1;
      --bs-btn-hover-bg: #6B9BEA;
      --bs-btn-hover-border-color: #6B9BEA;
      --bs-btn-active-bg: #6B9BEA;
      --bs-btn-active-border-color: #6B9BEA;
  }
  </style>
  </head>
  <body>
    <div
      style="
        height: 926px;
        width: 428px;
        margin: 0 auto;
        padding: 50px 10px 100px;
      "
      class="d-flex flex-column overflow-auto"
    >
      <div class="row mb-2">
        <svg
          class="col ml-0 pl-0"
          width="30"
          height="50"
          viewBox="45 0 30 50"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <rect width="50" height="50" rx="15" fill="#92B4EC" />
          <path
            d="M33 11.8606L30.4216 9L16 25L30.4216 41L33 38.1394L21.1568 25L33 11.8606Z"
            fill="white"
          />
        </svg>
        <!-- <a href="http://127.0.0.1:8000/orders/order_create/"> 이미지 </a> -->
        <!-- <a href="{% url 'orderapp:order_create' %}"> 이미지 </a> -->
        <h3 class="col d-flex justify-content-center align-items-center mb-0">
          결제
        </h3>
        <div class="col invisible">right</div>
      </div>
      <div class="h-100">{% block content %} {% endblock %}</div>
    </div>
  </body>
</html>

orderapp/templates/orderapp/cash.html
{% extends 'orderapp/base_payment.html' %} {% block content %}

  <div class="set2">
    <h1>현금결제</h1>
  </div>
  <br />

  <div class="set3">
    <h2>주문이 완료되었습니다.</h2>
  </div>

  <div class="set4">
    <a href="{% url 'orderapp:order_report' %}">주문 기록</a>
  </div>
</div>
{% endblock %}

orderapp/templates/orderapp/chicken_detailPage.html
{% extends 'base3.html' %}

{% block content %}

    <div class="set2">
        <h4>후라이드 치킨</h4>
    </div>
    
    <div >
        <p>배달비(+3000원)</p>
        <h4>총 금액: 19,000원</h4>
    </div>

    <div class="set4">
          
        <a href="{% url 'orderapp:order_create' %}"
               class="btn btn-primary rounded-pill col-3">
                결제
        </a>
    </div>
    


{% endblock %}

orderapp/templates/orderapp/credit_card.html
{% extends 'base2_2.html' %}

{% block content %}

    <div class="set2">
        <h1>카드결제</h1>
    </div><br />

    <div class="set3">
        <h2>주문이 완료되었습니다.</h2>
    </div>

    <div class="set4">
        <a href="{% url 'orderapp:order_report' %}">주문 기록</a>
    </div>
</div>

</div>

{% endblock %}

orderapp/templates/orderapp/menu_choice.html
{% extends 'orderapp/base.html' %} {% block content %}

<div class="post">
  <div class="date">{{ menu }}</div>
</div>
{% endblock %}

orderapp/templates/orderapp/order_create.html
{% extends 'orderapp/base_payment.html' %} {% block content %}
<div class="h-100 d-flex flex-column justify-content-evenly text-center text-blue">
  <div>
     <!-- Button trigger modal -->
    <button data-bs-toggle="modal" data-bs-target="#modal" type="button" class="py-2 w-100 btn btn-secondary shadow">
      <a class="text-decoration-none h2 text-dark">

        계좌이체

      </a>

    </button>

    <!-- Modal -->

    <div class="modal fade" id="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" 
    aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div style="height: 500px;" class="modal-content bg-secondary bg-opacity-75">
        <div class="modal-header justify-content-center border-secondary">
          <h3 class="modal-title text-white" id="modalLabel">
            주문 전 미션
          </h3>
        </div>
        <div class="modal-body d-flex justify-content-center align-items-center text-white display-3 p-5">물 300ml를
          <br />마셔주세요!</div>
        <div class="modal-footer row m-1 justify-content-center border-secondary">
          <button type="button" class="col btn btn-primary"><a href="{% url 'orderapp:transfer' %}">완료</a></button>
          <button type="button" class="col btn btn-secondary text-dark" data-bs-dismiss="modal">
            결제 취소
          </button>
        </div>
      </div>
    </div>
  </div>  



    <button data-bs-toggle="modal" data-bs-target="#modal" type="button"
      class="my-3 py-2 w-100 btn btn-secondary shadow">
      <a class="text-decoration-none h2 text-dark" >
        카드결제(현장)
      </a>
    </button>

    <div class="modal fade" id="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" 
    aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div style="height: 500px;" class="modal-content bg-secondary bg-opacity-75">
        <div class="modal-header justify-content-center border-secondary">
          <h3 class="modal-title text-white" id="modalLabel">
            주문 전 미션
          </h3>
        </div>
        <div class="modal-body d-flex justify-content-center align-items-center text-white display-3 p-5">물 300ml를
          <br />마셔주세요!</div>
        <div class="modal-footer row m-1 justify-content-center border-secondary">
          <a href="{% url 'orderapp:credit_card' %}"><button type="button" class="col btn btn-primary">완료</button></a>
          <button type="button" class="col btn btn-secondary text-dark" data-bs-dismiss="modal">
            결제 취소
          </button>
        </div>
      </div>
    </div>
  </div>  

    <button data-bs-toggle="modal" data-bs-target="#modal" type="button" class="py-2 w-100 btn btn-secondary shadow">
      <a class="text-decoration-none h2 text-dark">
        현금결제(현장)
      </a>
    </button>

    <div class="modal fade" id="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" 
    aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div style="height: 500px;" class="modal-content bg-secondary bg-opacity-75">
        <div class="modal-header justify-content-center border-secondary">
          <h3 class="modal-title text-white" id="modalLabel">
            주문 전 미션
          </h3>
        </div>
        <div class="modal-body d-flex justify-content-center align-items-center text-white display-3 p-5">물 300ml를
          <br />마셔주세요!</div>
        <div class="modal-footer row m-1 justify-content-center border-secondary">
          <a href="{% url 'orderapp:cash' %}"><button type="button" class="col btn btn-primary">완료</button></a>
          <button type="button" class="col btn btn-secondary text-dark" data-bs-dismiss="modal">
            결제 취소
          </button>
        </div>
      </div>
    </div>
  </div>  

    <!-- <div class="modal fade" id="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"  
      aria-labelledby="modalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div style="height: 500px;" class="modal-content bg-secondary bg-opacity-75">
          <div class="modal-header justify-content-center border-secondary">
            <h3 class="modal-title text-white" id="modalLabel">
              주문 전 미션
            </h3>
          </div>
          <div class="modal-body d-flex justify-content-center align-items-center text-white display-3 p-5">물 300ml를
            <br />마셔주세요!</div>
          <div class="modal-footer row m-1 justify-content-center border-secondary">
            <button type="button" class="col btn btn-primary">완료</button>
            <button type="button" class="col btn btn-secondary text-dark" data-bs-dismiss="modal">
              결제 취소
            </button>
          </div>
        </div>
      </div>
    </div>-->

    </br></br></br></br></br></br></br>

    <h2>
      이번 달 총 결제금액은<br />
      {{menu}}원 입니다
    </h2>
  </div>
  {% endblock %}

  <!-- modal이 적용되긴 하는데 계속 클릭하면 나오지 않고 새로고침해야지 나옴. -->
  <!-- 윗 문제 고침 -->

orderapp/templates/orderapp/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

orderapp/templates/orderapp/order_report.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="./Order_report.css">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order_report</title>
</head>

<body>
    <div class="set">
        <div class="set1">
            <div class="item1">
                <a href="/"><svg width="50" height="50" viewBox="0 0 50 50" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <rect width="50" height="50" rx="15" fill="#FFE699" />
                    <path
                        d="M33.3334 11.0821L30.8056 8.16309L16.6667 24.4896L30.8056 40.8161L33.3334 37.8972L21.7224 24.4896L33.3334 11.0821Z"
                        fill="black" />
                </svg></a>
            </div>
            <div class="item1">
                <h1>주문 기록</h1>
            </div>
        </div>

        <div class="set2">
        <h2>주문 접수 중</h2></div>

        <div class="set3">
        
            <h2>우리동네 치킨</h2>
            <br />
            <h3>후라이드 치킨</h3>
            <p>옵션:뼈</p>
            <h3>총 금액: 19,000원</h3>
        </div>

        <div class="set4">
        <h2>과거 주문목록</h2></div>
        
        <div class='set5'>
            <h2>우리동네 치킨</h2>
            <br />
            <h3>후라이드 치킨</h3>
            <p>옵션:순살</p>
            <h3>총 금액: 20,000원</h3>
        </div>


    </div>
</body>

</html>

orderapp/templates/orderapp/transfer.html
{% extends 'base2_2.html' %}

{% block content %}

<div class="set2">
    <h1>계좌이체</h1>
</div>

<div class="set3">
    <h3>매장의 계좌번호는</h3>
    <h3>신한은행</h3>
    <h3>110-5711-2869 입니다.</h3>
    <p>결제 완료 후 5분 내 입금 시 주문완료됩니다.</p>
    <p>주문 완료 후 취소할 수 없습니다.</p>
</div>

<div class="set4">
    <a href="{% url 'orderapp:order_report' %}">주문 기록</a>
</div>

{% endblock %}