Vium/Vium/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('accountapp.urls')),
    path('restaurants/', include('restaurantapp.urls')),
    path('orders/', include('orderapp.urls')),
    path('register/', user_views.register, name='register'),
    path('users/', include('users.urls')),
]

Vium/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('accountapp.urls')),
    path('restaurants/', include('restaurantapp.urls')),
    path('orders/', include('orderapp.urls')),
]

orderapp/urls.py
from django.urls import path

from orderapp.views import cash, credit_card, transfer, menu_choice, order_create,base3,cash,order_report


app_name = 'orderapp'

urlpatterns = [
    path('menu_choice/', menu_choice, name='menu_choice'),
    path('order_create/', order_create, name='order_create'),
    path('cash/', cash, name='cash'),
    path('credit_card/', credit_card, name='credit_card'),
    path('transfer/', transfer, name='transfer'),
    path('base3/', base3, name='base3'),
    path('cash/', cash, name='cash'),
    path('order_report/', order_report, name='order_report'),

]

restaurantapp/urls.py
from django.urls import path

from restaurantapp.views import 

app_name = 'restaurantapp'

urlpatterns = [

]

restaurantapp/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# Create your models here.

class Category(models.TextChoices):
    ONE = '1인분'
    JAPANESE = '일식'
    CHINESE = '중식'
    CHICKEN = '치킨'
    KOREAN = '한식'
    CAFE = '카페디저트'
    SNACK = '분식'
    PIZZA = '피자'
    WESTERN = '양식'
    MEAT = '고기구이'
    ASIAN = '아시안'
    FASTFOOD = '패스트푸드'
    MIDNIGHT = '야식'
    LUNCHBOX = '도시락'
    VEGAN = '채식'


class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    payment_methods = models.CharField(max_length=255) #list
    delivery_time = models.PositiveIntegerField()
    delivery_charge = models.PositiveIntegerField()
    min_order_price = models.PositiveIntegerField()
    categories = models.CharField(max_length=20) #list
    reorder_count = models.PositiveIntegerField(default=0) #재주문횟수

    image = models.ImageField(upload_to='restaurant_image', null=True, blank=True)
    business_name = models.CharField(max_length=255)
    company_registration_number = models.CharField(max_length=255)
    open_time = models.TimeField()
    close_time = models.TimeField()
    tel_number = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    origin_information = models.TextField()
    allergy_notification = models.TextField()

    def __str__(self):
        return f'({self.id}){self.name}'


def menu_img_path(instance, filename):
    filename = filename.split('?')[0]
    return f'menu_img/{filename}'


class Menu(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='menu_image', null=True, blank=True, max_length=400)
    caption = models.CharField(max_length=255)
    price = models.PositiveIntegerField()

restaurantapp/forms.py
from django.db import models
from django.forms import ModelForm

from orderapp.models import Order
from restaurantapp.models import Menu, Restaurant


def remaining_time(delivery_time, restaurant_id):
    receipt_complete_count = Order.objects.filter(restaurant_id=restaurant_id, status='접수 완료').count() // 3
    delivery_time += receipt_complete_count * (delivery_time // 2)
    return f'{delivery_time}~{delivery_time + 10}분'


class MenuDetailForm(ModelForm):
    class Meta:
        model = Menu
        fields = ('id', 'name', 'image', 'caption', 'price', 'option_group')


class MenuListForm(ModelForm):
    class Meta:
        model = Menu
        fields = ('id', 'name', 'image', 'caption', 'menu_group_id', 'price')


class RestaurantDetailForm(ModelForm):
    delivery_time = models.CharField()

    def get_delivery_time(self, obj):
        return remaining_time(obj.delivery_time, obj.id)

    class Meta:
        model = Restaurant
        fields = ('id', 'name', 'image', 'open_time', 'close_time', 'tel_number', 'address',
                  'min_order_price', 'payment_methods', 'business_name', 'company_registration_number',
                  'origin_information', 'allergy_notification', 'delivery_charge', 'delivery_time', 'reorder_count')


class RestaurantListForm(ModelForm):
    delivery_time = models.CharField()
    reorder_count = models.IntegerField()

    def get_delivery_time(self, obj):
        return remaining_time(obj.delivery_time, obj.id)

    class Meta:
        model = Restaurant
        fields = ('id', 'name', 'reorder_count', 'image', 'delivery_charge', 'delivery_time', 'min_order_price')

restaurantapp/views.py
from django.shortcuts import render

restaurantapp/templates/restaurantapp/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h4>오늘 소비한 칼로리</h4>
    <h2>{{ consumed_calorie }}kcal</h2>

    <a href="{% url 'orderapp:order_list' %}"
           class="btn btn-primary rounded-pill col-3">
        주문 기록
    </a>

    <a href="{% url 'restaurantapp:list' %}"
           class="btn btn-primary rounded-pill col-3">
        {{ Category }}
    </a>

    <p>
        이번 달 총 결제 금액은 {{ month_total_price }}원 입니다.
    </p>
</head>
<body>

</body>
</html>

restaurantapp/templates/restaurantapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h4>가게정보</h4>
    <p>영업시간 {{ open_time }}~{{ close_time }}</p>
    <p>전화번호 {{ tel_num }}</p>
    <p>주소 {{ address }}</p>
    <p>상호명 {{ business_name }}</p>
    <P>사업자등록번호 {{ company_registration_number }}</P>

    <h4>식품정보</h4>
    <p>원산지정보 {{ origin_information }}</p>
    <p>알레르기정보 {{ allergy_notification }}</p>
</head>
<body>

</body>
</html>

restaurantapp/templates/restaurantapp/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><p>{{ Category }}</p>

    <h4>오늘 소비한 칼로리</h4>
    <h3>{{ consumed_calorie }}kcal</h3>

    <h5>{{ name }}</h5>
    <h6>{{ reorder_count }}</h6>
    <h6>{{ delivery_time }}{{ delivery_charge }}</h6>
</head>
<body>

</body>
</html>

restaurantapp/templates/restaurantapp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h5>{{ name }}</h5>
    <h6>배달시간</h6> <p>{{ delivery_time }}</p>
    <h6>배달요금</h6> <p>{{ delivery_charge }}</p>
    <h6>결제방법</h6> <p>{{ payment_method }}</p>
    <h6>최소주문</h6> <p>{{ min_order_price }}</p>
    <h6>재주문 +{{ reorder_count }}</h6> <a href="{% url 'restaurantapp:detail' %}"
           class="btn btn-primary rounded-pill col-3">가게,원산지 정보</a>

    <a href="{% url 'orderapp:menu_choice' %}"
           class="btn btn-primary rounded-pill col-3">{{ menu }}</a>
</head>
<body>

</body>
</html>

restaurantapp/templates/restaurantapp/restaurant_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

restaurantapp/templates/restaurantapp/restaurant_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

restaurantapp/templates/restaurantapp/restaurant_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>